name: morham 2
favicon: null
layout_spectrum: 0.5949809136800468
typography_spectrum: 0.9871922575403005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.953842589398846
  lightness: 0.8330875774845481
  saturation: 0.21183244255371392
  rhythmicContrast: 0.8650099351070821
purpose: []
